Fix format-fix runs on Linux (https://redirect.github.com/duckdb/duckdb/pull/18827)
I was having troubles with the mainline `format.py` script. `make
format-fix` was printing file paths, but did not do any actual
formatting.

JDBC and ODBC Scanner formatting, that use the same `clang_format
11.0.1` but another version of `format.py` (simpistic, non-parallel
one), were working fine at the same time.

Found the problem with `format.py` runs when `os.rename()` call was
failing with the following exception, that was not printed/reported,
because it was thrown from background threads:

```python
Traceback (most recent call last):
  File "/home/alex/projects/duck/duckdb-mysql/./duckdb/scripts/format.py", line 434, in <module>
    format_file(f.filename, f.full_path, f.directory, f.ext)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/projects/duck/duckdb-mysql/./duckdb/scripts/format.py", line 383, in format_file
    os.rename(tmpfile, full_path)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 18] Invalid cross-device link: '/tmp/726068ed-7cdf-4917-bf4d-374fae67b1f1' -> '/home/alex/projects/duck/duckdb-mysql/src/mysql_utils.cpp'
```

It appeared that `os.rename()` is not robust enough and changing it to
`shutil.move()` (that is doing copy+delete) helped to fix this.
Additonally added printing of the background errors to stdout.

Upstream-commit: https://github.com/duckdb/duckdb/commit/5873cd98f511f3bbfb7015716d05cf7470f74d7a