[Fix] Add the new extension loader symbol to the bundled / gathered libraries (https://redirect.github.com/duckdb/duckdb/pull/20539)
Currently, using `make gather-libs` or `make bundle-library` on
`v1.5-variegata` breaks when linking to, e.g., duckdb-go with the
following missing symbol:

```
Undefined symbols for architecture arm64:
  "duckdb::ExtensionHelper::LoadAllExtensions(duckdb::DuckDB&)", referenced from:
      duckdb::DuckDB::DuckDB(char const*, duckdb::DBConfig*) in libduckdb_bundle.a[245](ub_duckdb_main.cpp.o)
ld: symbol(s) not found for architecture arm64
```

Upstream-commit: https://github.com/duckdb/duckdb/commit/1199e76cb400cfc9a566db56f716789d5da5d248