Temporarily excluding `Build Pyodide wheel` for Python 3.11 because it fails to build `WASM` wheels  (https://redirect.github.com/duckdb/duckdb/pull/18508)
`InvokeCI` fails to `build wasm wheel` for Python 3.11:
```
ERROR: Failed to load environment variables from Makefile.envs
```

I'm opening this PR to temporarily skip building it for 3.11 in `main`.

Upstream-commit: https://github.com/duckdb/duckdb/commit/cc930c93aa2589831582177a3f9c8d2ce24daaf6