Fix linux base and extension deployment on main (https://redirect.github.com/duckdb/duckdb/pull/21554)
### Fix linux base build

Fix linux base
[build](https://github.com/duckdb/duckdb/actions/runs/23416834562/job/68114256859#step:9:337)
on branch `main`:
```
[...]
-- Load extension 'core_functions' from '/home/runner/work/duckdb/duckdb/extensions' @ c43ab41ad4
CMake Error at CMakeLists.txt:1354 (add_subdirectory):
Error:   add_subdirectory given source
  "/home/runner/work/duckdb/duckdb/extension/fts" which is not an existing
  directory.
[...]
```
The extension `fts` did not exist (yet) for the commit
`c43ab41ad426f758cb0b246c410c21960938910c` and caused the build to fail.

The commit was too old:
```
commit c43ab41ad426f758cb0b246c410c21960938910c
Merge: f249c2ce5c 3e7292aa5f
Author: Mark <mark.raasveldt@gmail.com>
Date:   Thu May 15 22:32:08 2025 +0200

    Remove spatial from OSX Relassert (https://redirect.github.com/duckdb/duckdb/pull/17509)
    
    This was added recently, but has never worked
```
and came from the `gh run ...` command that relied on an earlier
workflow setup.

I've updated the `gh run` command and moved it to the makefile so we can
easily test the same command locally.

### Fix extension deployment and upload in parallel

The extension deploy step did
[not](https://github.com/duckdb/duckdb/actions/runs/23416836692/job/68141948484)
upload any extensions because the file path layout slightly changed by
upgrading the download-artifact action version.

I changed:
- download action to use the expected file path layout.
- print the number of found extension files.
- the script to fail when no files are found.

Fixes: https://github.com/duckdblabs/duckdb-internal/issues/8445.

Also, I made the deploy script run the uploads in parallel (up to
`CI_CPU_COUNT`). This should reduce the time to upload all extensions
from `22 min` to roughly `22/4=5.5 min`.

### Clean up

Fixes https://github.com/duckdblabs/duckdb-internal/issues/7627 (windows
32-bit's CI job was already commented, but now also removed).

Upstream-commit: https://github.com/duckdb/duckdb/commit/f41a50709aa1c404b43d9c6fa7a75c95f8df5c9c