chore: Add physical type translations for new timestamp types (https://redirect.github.com/duckdb/duckdb/pull/15472)
Follow-up to https://redirect.github.com/duckdb/duckdb/pull/14818.

This changes the error message in
https://github.com/duckdb/duckdb-r/pull/716#discussion_r1897502922 from

```
Error: Not implemented Error: Unimplemented type for cast (INVALID -> INT64)
```

to the slightly more legible 

```
Error: Not implemented Error: Unimplemented type for cast (INT64 -> INT64)
```

I do wonder why this error message refers to physical types instead of
logical types. Should the formatter be using a variant of
`GetArgumentType()` instead of `GetTypeId()` ?

Upstream-commit: https://github.com/duckdb/duckdb/commit/7b37d47595489f987d695318a8a13bda33a98a05