[minor] Address more compile warnings (https://redirect.github.com/duckdb/duckdb/pull/20232)
I usually do dev on ubuntu with libstdc++/gcc and compile with reldebug
build.
But when I switch to my mac, with toolchain setup libc++/clang and
compiling with debug build, I often spot some compilation errors.
This PR should fix all but one compilation warnings, which I don't have
a good idea :(
```sh
/Users/hjiang/Desktop/duckdb/src/storage/block_allocator.cpp:203:46: warning: declaration requires an exit-time destructor [-Wexit-time-destructors]
  203 |         thread_local BlockAllocatorThreadLocalState local_state(block_allocator);
      |                                                     ^
```

Upstream-commit: https://github.com/duckdb/duckdb/commit/3543aaffe88bd44f1d5a359dfaff13780953c63e