Fix nightly tests and ignore very slow tests for HASH_ZERO=1 (https://redirect.github.com/duckdb/duckdb/pull/22509)
### Clean up

- Remove duplicate `cleanup_runner` actions.
- Upgrade some nightly tests jobs to `ubuntu:24.04`.

### Fix some CI jobs

- Fix `function.GetArguments()` refactor for `SMALLER_BINARY=1`. Fixes
https://github.com/duckdblabs/duckdb-internal/issues/9140.
- Fix missing `iostream` in `test_utils` extension by bumping extension
tag.

### Ignore slow tests for `HASH_ZERO=1`

- Ignore 7 very slow tests with expected hash-collisions causing
quadratic runtime.
- Report slow (>30 sec) tests for `HASH_ZERO=1` in CI, and fail a test
after 2 min.

We can find slow tests locally (or in CI), using:
```
$ make unittest_relassert T="--track-runtime 30 --batch-timeout 120 --test-config=test/configs/hash_zero.json"
found 4105 tests
config: test_flags=--test-config test/configs/hash_zero.json, workers=6, retry=0, max_retries=4, batch_size=1, batch_timeout_seconds=120.0, runtime_threshold_seconds=30
..................................
test/sql/join/inner/test_prefix_range_filter_pushdown_strinline.test took 59.97s
.......
test/issues/general/test_21431.test took 120.07s
.
test/sql/settings/operator_memory_limit.test took 120.05s
........ [ 50%]
..........
test/sql/insert/insert_by_name.test took 120.03s
..
test/sql/join/inner/test_prefix_range_filter_pushdown.test took 120.06s
.....................................
test/sql/table_function/duckdb_eviction_queues.test took 58.77s
. [100%]
error: found 4 test batch failures in 279s
```

Some of the ignored tests took more than 10 minutes to run, because 600s
is the original test timeout used for `HASH_ZERO=1`. See also these two
issues:

Fixes https://github.com/duckdblabs/duckdb-internal/issues/9083.
Fixes https://github.com/duckdblabs/duckdb-internal/issues/9103.

### `BWC Test` was skipped because `Build DuckDB` failed

The CI jobs for `BWC Test` were
[skipped](https://github.com/duckdb/duckdb/actions/runs/25410966728/job/74533817019)
because the job `Build DuckDB` failed for `NightlyTests.yml`.

I'll look into the BWC test job failures another time.

Upstream-commit: https://github.com/duckdb/duckdb/commit/43b4d55aeba22203fb8f00c46d699ba663a9e4cd