Fix GCC-12 build and notify external repo CI jobs (https://redirect.github.com/duckdb/duckdb/pull/22184)
The CI job `Linux static libraries (amd64)` uses GCC-12 and reported an
[error](https://github.com/duckdb/duckdb/actions/runs/24698539753/job/72236578826#step:3:512)
in CI:
```c++
In file included from build/release/src/planner/filter/ub_duckdb_planner_filter.cpp:6:
src/planner/filter/expression_filter.cpp: In static member function ‘static duckdb::unique_ptr<duckdb::Expression> duckdb::ExpressionFilter::CreateInExpression(duckdb::unique_ptr<duckdb::Expression>, duckdb::vector<duckdb::Value>)’:
src/planner/filter/expression_filter.cpp:43:16: error: could not convert ‘result’ from ‘unique_ptr<duckdb::BoundOperatorExpression,default_delete<duckdb::BoundOperatorExpression>,[...]>’ to ‘unique_ptr<duckdb::Expression,default_delete<duckdb::Expression>,[...]>’
   43 |         return result;
      |                ^~~~~~
      |                |
      |                unique_ptr<duckdb::BoundOperatorExpression,default_delete<duckdb::BoundOperatorExpression>,[...]>
```

The nightly build status workflow did not receive the dispatch call due
to a type
[error](https://github.com/duckdb/duckdb/actions/runs/24698539753/job/72270710106#step:2:111)
(expected string instead of a bool):
```json
* Connection https://redirect.github.com/duckdb/duckdb/pull/0 to host api.github.com left intact
{
  "message": "Invalid value for input 'should_publish'",
  "documentation_url": "https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event",
  "status": "422"
}
```

I've also added curl retry logic (for robustness), and let an HTTP
response failure also mark the CI job as failed.

Upstream-commit: https://github.com/duckdb/duckdb/commit/3cd75bce1817dacf0b7afd09a13541bc6876c594