Add support for `MMAP` and `DIRECT_IO` I/O modes (https://redirect.github.com/duckdb/duckdb/pull/22988)
This PR introduces support for setting the `IO_MODE` in which an
attached database is opened. This can be one of three options:

* **BUFFERED_IO**: Use standard buffered I/O, the default setting (and
previously what was effectively always used).
* **MMAP**: Use `mmap` as a back-end for reads and writes. Instead of
reading into buffers that we cache explicitly we rely on the OS' page
cache to do the caching of data in the files.
* **DIRECT_IO**: Use direct I/O. This bypasses the OS' page cache
entirely and reads data directly into buffers.

Usage example:

```sql
ATTACH 'my_file.db' AS mmaped_db (IO_MODE 'MMAP')
```

In general these settings should not affect usage - only performance.
All operations are possible on all of these I/O modes with one
exception: we do not support `mmap` together with encrypted files. That
is because DuckDB relies on decrypting files into buffers as part of the
`Read()` operation, which we do not do when using `MMAP`.

For writing, we rely on reserving address space in the mmaped file
up-front. This allows us to just hand out pointers in the file to write
to instead of having to do any extending / remapping of the file. By
default we reserve address space is equal to `max(256GB, 2 * file_size)`
- i.e. usually we would reserve 256B, unless the file is larger than
128GB in which case we reserve twice the files' size. If this size is
exceeded during a write we throw an error. The reserved address space
can be manually configured using the `mmap_reserve_size` parameter:

```sql
ATTACH 'my_file.db' AS mmaped_db (IO_MODE 'MMAP', MMAP_RESERVE_SIZE '10GB')
```

Upstream-commit: https://github.com/duckdb/duckdb/commit/17997b74e7e0117b0116012db152689d291d8918