Remove delta from extensions built on a nightly basis (vs main branch) (https://redirect.github.com/duckdb/duckdb/pull/16795)
Currently fails like:
```
[6/1091] Performing configure step for 'delta_kernel'
FAILED: rust/src/delta_kernel-stamp/delta_kernel-configure /Users/runner/work/duckdb/duckdb/build/release/rust/src/delta_kernel-stamp/delta_kernel-configure
cd /Users/runner/work/duckdb/duckdb/build/release/rust/src/delta_kernel && /opt/homebrew/bin/cmake -E env --unset=CC --unset=CXX --unset=LD env cargo update -p chrono --precise 0.4.38 && /opt/homebrew/bin/cmake -E touch /Users/runner/work/duckdb/duckdb/build/release/rust/src/delta_kernel-stamp/delta_kernel-configure
    Updating crates.io index
    Updating crates.io index
error: failed to select a version for the requirement `chrono = "^0.4.40"`
candidate versions found which didn't match: 0.4.38
location searched: crates.io index
required by package `parquet v54.3.0`
    ... which satisfies dependency `parquet_54 = "^54"` (locked to 54.3.0) of package `delta_kernel v0.7.0 (/Users/runner/work/duckdb/duckdb/build/release/rust/src/delta_kernel/kernel)`
    ... which satisfies path dependency `delta_kernel` (locked to 0.7.0) of package `acceptance v0.7.0 (/Users/runner/work/duckdb/duckdb/build/release/rust/src/delta_kernel/acceptance)
```

Upstream-commit: https://github.com/duckdb/duckdb/commit/4574d78157c1d09e6963f784afd03041954caa10