Fix: list_concat(NULL) returns NULL (https://redirect.github.com/duckdb/duckdb/pull/19565)
Fixes: https://github.com/duckdb/duckdb-fuzzer/issues/4296

`SELECT list_concat(NULL)` was throwing:
```
ABORT THROWN BY INTERNAL EXCEPTION: Failed to find function array_cat(VARCHAR)
```

Now it returns `NULL` which is consistent with our other nested
functions. However the previous implementation, probably by
conincidence, matched PostgreSQL:
```sql
postgres=# select array_cat(NULL);
ERROR:  function array_cat(unknown) does not exist
LINE 1: select array_cat(NULL);
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

`SELECT list_concat(NULL, NULL)` also returned an error before but this
has now been changed to also return `NULL`. This does match PostgreSQL:
```sql
postgres=# select array_cat(NULL, NULL);
 array_cat 
-----------
 
(1 row)
```

Upstream-commit: https://github.com/duckdb/duckdb/commit/b1cbd31c8ff4784cd86548fff9a7786e64bde147