Fix GCC 12 issue and use ref for consistent checkouts (https://redirect.github.com/duckdb/duckdb/pull/22240)
Fix GCC 12 compilation issue with missing `std::move()`:
```
In file included from /home/runner/work/duckdb/duckdb/build/release/src/function/cast/ub_duckdb_func_cast.cpp:18:
/home/runner/work/duckdb/duckdb/src/function/cast/union_casts.cpp: In function ‘duckdb::unique_ptr<duckdb::FunctionLocalState> duckdb::InitToUnionLocalState(CastLocalStateParameters&)’:
/home/runner/work/duckdb/duckdb/src/function/cast/union_casts.cpp:195:24: error: could not convert ‘result’ from ‘unique_ptr<duckdb::StructCastLocalState,default_delete<duckdb::StructCastLocalState>,[...]>’ to ‘unique_ptr<duckdb::FunctionLocalState,default_delete<duckdb::FunctionLocalState>,[...]>’
  195 |                 return result;
      |                        ^~~~~~
      |                        |
      |                        unique_ptr<duckdb::StructCastLocalState,default_delete<duckdb::StructCastLocalState>,[...]>
```

### Use `github.sha` as ref

Use the same git commit to have a consistent checkout in all CI jobs.

For example, a branch `main` (or v1.5) can change after the CI run
started and each checkout would look at "the current branch state" which
drifts from the original commit used for the CI run.

Fixes https://github.com/duckdblabs/duckdb-internal/issues/7412.

Upstream-commit: https://github.com/duckdb/duckdb/commit/245e7819e630978d48be6a5fc242317e8d52dde8