Fix an if statement that is always True (https://redirect.github.com/duckdb/duckdb/pull/15630)
% `python3 -c "print((isinstance, str))"`
```
(<built-in function isinstance>, <class 'str'>)
```
% `python3 -c "print(bool((isinstance, str)))"`
```
True
```
% `ruff check ---select=E9,F63,F7`
```
Error: scripts/python_helpers.py:20:8: F634 If test is a tuple, which is always `True`
```
Current state:
* Always return `normalize(path)`

Proposed state:
* Return `normalize(path)` if `path` is a `str` otherwise raise an
`Exception` which should probably be a `TypeError` instead of a generic
`Exception`.

Upstream-commit: https://github.com/duckdb/duckdb/commit/003dfd89ad2516bae6c5f6e04b5ec45bcb171a11