Fix bwc test jobs (https://redirect.github.com/duckdb/duckdb/pull/22529)
- Compute version matrix using git tags instead of using hardcoded
version list.
- Group bwc test jobs by minor duckdb version.
- Fix test-utils commit.

We should not use `Update extension` commits because that
[fails](https://github.com/duckdb/duckdb/actions/runs/25500841929/job/74839369343#step:8:111):
```
  File "/home/runner/work/duckdb/duckdb/test/bwc/runner.py", line 201, in do_run_test
    raise RuntimeError(
RuntimeError: test-utils extension version mismatch:
v1.1.0 is @ 5b9c733 and v1.6.0-dev5484 is @ 7074208
Error: Process completed with exit code 1.
```

### CI failure is unrelated

```
Run python scripts/plan_cost_runner.py --old build/base/release/duckdb --new build/current/release/duckdb --dir=benchmark/imdb_plan_cost
tcache_thread_shutdown(): unaligned tcache chunk detected
Aborted (core dumped)
```

Upstream-commit: https://github.com/duckdb/duckdb/commit/994592b8922be78e00de768310416de0d50149cf