Revamp extension build / patching system for better local development, enabled when `DUCKDB_NEW_EXTENSION_BUILD=1` is defined (https://redirect.github.com/duckdb/duckdb/pull/22063)
This PR creates an initial version of a better extension build /
patching system for local development, as the current system is a bit of
a mess.

* We need to have `USE_MERGED_VCPKG_MANIFEST=1 BUILD_ALL_EXT=1 make
extension_configuration` to generate a merged vcpkg manifest list. This
clones all extension repositories in `build/extension_configuration/`
* We need to then run `USE_MERGED_VCPKG_MANIFEST=1 BUILD_ALL_EXT=1 make
reldebug`, which clones the extension repositories again in
`build/reldebug/_deps/` and applies the patches. Patches are left as
uncommitted / unstaged in the repositories.
* If we then want to actually change these repositories in order to fix
builds or generate new patches, we need to jump through a bunch of hoops
to do so - the dev experience is very poor. In addition, this system
gravitates towards generating a single giant patch which leads to
terrible merge conflicts.

This PR introduces a new build system (that ideally eventually replaces
the old one) that addresses these issues:

* Extensions are cloned once in `extension/external/`, so if we build
delta this will end up in `extension/external/delta`
* `USE_MERGED_VCPKG_MANIFEST=1` is obsolete. If we are building any
extensions that require vcpkg we will automatically generate a
`vcpkg.json` file in `build/vcpkg.json` containing the merged vcpkg
manifests.
* Patches are now applied as commits in the repository with as commit
message the patch file name, e.g. `0001_fix1.patch`, `0002_fix2.patch`.
This allows subsequent development / fixes to be build on top of
previous patches.

### Development

If we perform development in the repo (e.g. make changes to
`extension/external/....`) - we have a few new workflows:

If we have uncommitted changes this error will be thrown:

```
ERROR: Extension 'delta' has uncommitted changes:
 M src/delta_extension.cpp
To resolve:
* FORCE_APPLY_PATCHES=1           — discard local changes and re-apply patches
* DUCKDB_SKIP_APPLYING_PATCHES=1  — skip patch checks and compile as-is
make: *** [sync_out_of_tree_extensions] Error 1
```

We can choose to either override our local changes and "restart" from
the current committed state using `FORCE_APPLY_PATCHES=1`, or just build
using `DUCKDB_SKIP_APPLYING_PATCHES=1`.

Alternatively, we can commit our changes with the name of a new patch,
e.g. `git commit -m "0002-my-fixes.patch`. This will then give us the
following error message:

```
ERROR: Extension 'delta' has unexpected local commits.
  Expected (patch commits): ['0001-vector-fix.patch']
  Found:                    ['0001-vector-fix.patch', '0002-my-fixes.patch']
To resolve:
* Delete extension/external/delta and re-run to re-sync
* FORCE_APPLY_PATCHES=1           — discard local changes and re-apply patches
* DUCKDB_SKIP_APPLYING_PATCHES=1  — skip patch checks and compile as-is
* EXPORT_EXTENSION_PATCHES=1     — export local commits as patch files
make: *** [sync_out_of_tree_extensions] Error 1
```

We can then run `EXPORT_EXTENSION_PATCHES=1 make reldebug` which will
export our changes to the relevant patch
(`.github/patches/extensions/delta/0002-my-fixes.patch`).

Upstream-commit: https://github.com/duckdb/duckdb/commit/b9ad51286a0e0eb0b61dbdc11ae8b94283b14549